global:
  scrape_interval: 15s
scrape_configs:
  - job_name: fiapx-api
    static_configs:
      - targets: [api:8000]
    metrics_path: /metrics
  - job_name: rabbitmq
    metrics_path: /metrics/per-object
    static_configs:
      - targets: [rabbitmq:15692]
  - job_name: fiapx-video-worker
    static_configs:
      - targets: [video-worker:8001]
  - job_name: fiapx-notification-worker
    static_configs:
      - targets: [notification-worker:8002]
