import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { catchError, of } from 'rxjs';
import { AppShellComponent } from '../../core/layout/app-shell.component';
import { Video, VideoStatus } from '../../core/models/video.model';
import { VideoService } from '../../core/services/video.service';

@Component({standalone:true,imports:[RouterLink,AppShellComponent],template:`<app-shell><a class="back-link" routerLink="/dashboard">‹ &nbsp; VOLTAR PARA MEUS VÍDEOS</a>@if(loading()){<div class="detail-skeleton"></div>}@else if(error()){<div class="state-message error-state">{{error()}} <a routerLink="/dashboard">Voltar ao dashboard</a></div>}@else if(video();as item){<div class="detail-layout"><div><div class="detail-preview thumb-default"><button class="play-button" aria-label="Visualizar vídeo">▶</button></div><div class="progress-title">Progresso</div><div class="timeline"><div class="timeline-line"></div>@for(step of timeline(item.status);track step.label){<div class="timeline-step" [class]="step.state"><span>{{step.state==='failed'?'×':step.state==='completed'?'✓':'•'}}</span><b>{{step.label}}</b><small>{{step.time}}</small></div>}</div></div><div class="detail-main"><div class="detail-heading"><h1>{{item.originalFilename}}</h1><b class="status" [class.success]="item.status==='COMPLETED'" [class.queued]="item.status==='QUEUED'" [class.failed]="item.status==='FAILED'">{{statusLabel(item.status)}}</b></div><p class="meta">▣ &nbsp;{{item.frameCount ?? '—'}} imagens &nbsp;&nbsp; ◷ &nbsp;Enviado em {{item.createdAt}}</p><p class="description">{{item.errorMessage || 'Detalhes do processamento deste vídeo.'}}</p><div class="detail-actions"><button class="primary-button" [disabled]="!item.downloadAvailable" (click)="download(item)">⇩ &nbsp; BAIXAR ZIP</button></div></div><aside class="specs"><h3>Detalhes</h3><dl><dt>ID</dt><dd>{{item.id}}</dd><dt>Duração</dt><dd>{{item.duration ?? '—'}}</dd><dt>Resolução</dt><dd>{{item.resolution ?? '—'}}</dd><dt>FPS</dt><dd>{{item.fps ?? '—'}}</dd><dt>Formato</dt><dd>{{item.format ?? '—'}}</dd><dt>Tamanho</dt><dd>{{item.resultSize ?? '—'}}</dd></dl></aside></div>}</app-shell>`})
export class VideoDetailsComponent {
  private readonly service=inject(VideoService); private readonly route=inject(ActivatedRoute); readonly video=signal<Video|null>(null); readonly loading=signal(true); readonly error=signal('');
  constructor(){this.route.paramMap.subscribe((params)=>{const id=params.get('id');if(!id){this.error.set('Vídeo não encontrado.');this.loading.set(false);return;}this.service.get(id).pipe(catchError(()=>{this.error.set('Não foi possível carregar este vídeo.');this.loading.set(false);return of(null);})).subscribe((item)=>{if(item)this.video.set(item);else if(!this.error())this.error.set('Vídeo não encontrado.');this.loading.set(false);});});}
  statusLabel(status:VideoStatus):string{return {UPLOADING:'Enviando',QUEUED:'Na fila',PROCESSING:'Processando',COMPLETED:'Concluído',FAILED:'Falhou'}[status];}
  timeline(status:VideoStatus){const order:VideoStatus[]=['UPLOADING','QUEUED','PROCESSING','COMPLETED'];const current=order.indexOf(status);return [{label:'Enviado',state:'completed',time:''},{label:'Na fila',state:current>=1?'completed':status==='FAILED'?'failed':'pending',time:''},{label:'Processando',state:status==='FAILED'?'failed':current>2?'completed':current===2?'active':'pending',time:''},{label:'Concluído',state:status==='COMPLETED'?'completed':'pending',time:''}];}
  download(video:Video):void{this.service.download(video.id).subscribe({next:(url)=>window.open(url,'_blank','noopener'),error:()=>this.error.set('Não foi possível iniciar o download.')});}
}
