import { HttpEventType, HttpErrorResponse } from '@angular/common/http';
import { Component, computed, DestroyRef, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { catchError, interval, of, Subscription, switchMap } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { AppShellComponent } from '../../core/layout/app-shell.component';
import { ALLOWED_VIDEO_EXTENSIONS, MAX_UPLOAD_SIZE_BYTES, POLLING_INTERVAL_MS } from '../../core/config/api.config';
import { Video, VideoStatus } from '../../core/models/video.model';
import { VideoService } from '../../core/services/video.service';
import { AuthService } from '../../core/auth/auth.service';

@Component({standalone:true,imports:[RouterLink,AppShellComponent],template:`
<app-shell [menuOpen]="menuOpen()" (toggleMenu)="menuOpen.set(!menuOpen())" (closeMenu)="menuOpen.set(false)">
<header class="topbar"><div><p class="page-kicker">VISÃO GERAL</p><h1>Processamento de vídeos</h1><p class="muted">Transforme seus vídeos em sequências de imagens.</p></div><div class="top-actions"><button class="icon-button" aria-label="Notificações" routerLink="/notifications">♧</button><span class="avatar">{{userInitials()}}</span><span class="user-name">{{auth.currentUser()?.name || 'Usuário'}}</span></div></header>
<div class="page-actions"><button class="primary-button" (click)="openUpload()">＋ &nbsp;ENVIAR NOVO VÍDEO</button></div>
@if (error()) { <div class="state-message error-state" role="alert">{{error()}} <button class="text-button" (click)="loadVideos()">TENTAR NOVAMENTE</button></div> }
@if (loading() && !videos().length) { <div class="video-grid">@for (item of [1,2,3]; track item) { <div class="video-card skeleton-card"><div class="thumb"></div><div class="card-content"><span class="skeleton-line"></span><span class="skeleton-line short"></span></div></div> }</div> }
@if (!loading() && !error() && !videos().length) { <div class="empty-state"><h2>Nenhum vídeo enviado ainda.</h2><p class="muted">Envie seu primeiro vídeo para começar.</p><button class="primary-button" (click)="openUpload()">ENVIAR PRIMEIRO VÍDEO</button></div> }
@if (activeVideos().length) { <section class="video-section"><div class="section-heading"><h2>Em processamento</h2><span>{{activeVideos().length}} vídeos</span></div><div class="video-grid">@for(video of activeVideos();track video.id){<a class="video-card" [routerLink]="['/videos',video.id]"><div class="thumb thumb-default"><button class="more-button" aria-label="Mais opções" (click)="$event.preventDefault()">⋮</button></div><div class="card-content"><strong class="truncate">{{video.originalFilename}}</strong>@if(video.status==='QUEUED'){<b class="status queued">Na fila · {{video.progress}}%</b>}@else{<div class="progress-row"><span class="progress-track"><span [style.width.%]="video.progress"></span></span><b>{{video.progress}}%</b></div><span class="card-note">◷ {{video.progressStage}}</span>}</div></a>}</div></section> }
@if (completedVideos().length) { <section class="video-section"><div class="section-heading"><h2>Finalizados</h2><span>{{completedVideos().length}} vídeos</span></div><div class="video-grid">@for(video of completedVideos();track video.id){<a class="video-card" [routerLink]="['/videos',video.id]"><div class="thumb thumb-default"><button class="more-button" aria-label="Mais opções" (click)="$event.preventDefault()">⋮</button></div><div class="card-content"><strong class="truncate">{{video.originalFilename}}</strong><b class="status success">● Concluído</b><div class="card-footer"><span>{{video.frameCount ?? '—'}} imagens • {{video.resultSize ?? '—'}}</span><button class="download-button" aria-label="Baixar ZIP" (click)="download(video, $event)">⇩</button></div></div></a>}</div></section> }
@if (failedVideos().length) { <section class="video-section"><div class="section-heading"><h2>Falhas</h2><span>{{failedVideos().length}} vídeos</span></div><div class="video-grid">@for(video of failedVideos();track video.id){<a class="video-card" [routerLink]="['/videos',video.id]"><div class="card-content"><strong class="truncate">{{video.originalFilename}}</strong><b class="status error">Falha no processamento</b><span class="card-note">{{video.errorMessage || 'Não foi possível processar este vídeo.'}}</span></div></a>}</div></section> }
@if(uploadOpen()){<section class="upload-panel" role="dialog" aria-modal="true" aria-labelledby="upload-title"><div class="panel-title"><h2 id="upload-title">Enviar novo vídeo</h2><button class="close-button" aria-label="Fechar" (click)="closeUpload()">×</button></div><div class="dropzone" [class.drag-over]="dragOver()" (dragover)="$event.preventDefault();dragOver.set(true)" (dragleave)="dragOver.set(false)" (drop)="onDrop($event)" (click)="fileInput.click()"><div class="cloud">☁</div><p>Arraste e solte seu vídeo aqui</p><span>ou</span><button class="outline-button" type="button">SELECIONAR ARQUIVO</button><input #fileInput hidden type="file" [accept]="accept" (change)="selectFile($event)"></div>@if(selectedFile()){<p class="file-selected">✓ {{selectedFile()!.name}}</p>}@if(uploadError()){<p class="field-error" role="alert">{{uploadError()}}</p>}<div class="panel-actions"><button class="secondary-button" (click)="closeUpload()">CANCELAR</button><button class="primary-button" [disabled]="!selectedFile() || uploading()" (click)="upload()">{{uploading() ? 'ENVIANDO…' : 'ENVIAR'}}</button></div><small>Formatos aceitos: MP4, MOV, AVI, MKV, WEBM • Máx. 500 MB</small></section>}
</app-shell>`})
export class DashboardComponent {
  private readonly service = inject(VideoService);
  readonly auth = inject(AuthService);
  readonly menuOpen=signal(false); readonly uploadOpen=signal(false); readonly selectedFile=signal<File | null>(null); readonly dragOver=signal(false); readonly uploading=signal(false); readonly uploadProgress=signal(0); readonly uploadError=signal(''); readonly loading=signal(true); readonly error=signal(''); readonly videos=signal<Video[]>([]); readonly accept=ALLOWED_VIDEO_EXTENSIONS.map((item) => `.${item}`).join(',');
  readonly activeVideos=computed(()=>this.videos().filter((v)=>v.status==='PROCESSING'||v.status==='QUEUED')); readonly completedVideos=computed(()=>this.videos().filter((v)=>v.status==='COMPLETED')); readonly failedVideos=computed(()=>this.videos().filter((v)=>v.status==='FAILED'));
  private readonly destroyRef=inject(DestroyRef); private polling?: Subscription;
  constructor() { this.startPolling(); this.auth.loadCurrentUser().pipe(catchError(() => of(null))).subscribe(); }
  userInitials(): string { const name=this.auth.currentUser()?.name?.trim(); return name ? name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase() : 'US'; }
  private startPolling(): void { this.polling?.unsubscribe(); this.polling=interval(POLLING_INTERVAL_MS).pipe(switchMap(()=>this.service.list().pipe(catchError(()=>of(null)))),takeUntilDestroyed(this.destroyRef)).subscribe((items)=>{this.loading.set(false);if(items){this.videos.set(items);this.error.set('');if(!items.some((item)=>item.status==='QUEUED'||item.status==='PROCESSING'))this.polling?.unsubscribe();}else if(!this.videos().length)this.error.set('Não foi possível carregar seus vídeos.');}); this.service.list().pipe(takeUntilDestroyed(this.destroyRef),catchError(()=>of(null))).subscribe((items)=>{this.loading.set(false);if(items){this.videos.set(items);this.error.set('');if(!items.some((item)=>item.status==='QUEUED'||item.status==='PROCESSING'))this.polling?.unsubscribe();}else if(!this.videos().length)this.error.set('Não foi possível carregar seus vídeos.');}); }
  loadVideos(): void { this.loading.set(true); this.startPolling(); }
  openUpload(): void { this.uploadError.set(''); this.uploadOpen.set(true); }
  closeUpload(): void { if(!this.uploading()) { this.uploadOpen.set(false); this.selectedFile.set(null); } }
  selectFile(event: Event): void { const file=(event.target as HTMLInputElement).files?.[0]; if(file)this.setFile(file); }
  onDrop(event: DragEvent): void { event.preventDefault(); this.dragOver.set(false); const file=event.dataTransfer?.files[0]; if(file)this.setFile(file); }
  private setFile(file: File): void { const ext=file.name.split('.').pop()?.toLowerCase(); if(!ext || !ALLOWED_VIDEO_EXTENSIONS.includes(ext)){this.uploadError.set('Formato de vídeo não suportado.');return;} if(file.size>MAX_UPLOAD_SIZE_BYTES){this.uploadError.set('O arquivo excede o tamanho permitido.');return;} this.uploadError.set('');this.selectedFile.set(file); }
  upload(): void { const file=this.selectedFile(); if(!file)return; this.uploading.set(true); this.service.upload(file).subscribe({next:(event)=>{if(event.type===HttpEventType.UploadProgress)this.uploadProgress.set(Math.round(100*(event.loaded/(event.total||file.size))));if(event.type===HttpEventType.Response){this.uploading.set(false);this.closeUpload();this.loadVideos();}},error:(err:HttpErrorResponse)=>{this.uploading.set(false);this.uploadError.set(err.status===413?'O arquivo excede o tamanho permitido.':err.status===503?'O serviço está temporariamente indisponível.':'Não foi possível enviar o vídeo.');}}); }
  download(video: Video,event: Event): void { event.preventDefault(); event.stopPropagation(); if(!video.downloadAvailable)return; this.service.download(video.id).subscribe({next:(blob)=>this.saveDownload(blob),error:()=>this.error.set('Não foi possível iniciar o download.')}); }
  private saveDownload(blob: Blob): void { const url=URL.createObjectURL(blob); const link=document.createElement('a'); link.href=url; link.download='frames.zip'; link.click(); URL.revokeObjectURL(url); }
}
